name: Update Prompts

on:
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Download file
        working-directory: ./assets
        run: curl -L -o _prompts.csv https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv

      - name: Check if file changed
        id: change
        working-directory: ./assets
        run: |
          if cmp --silent _prompts.csv prompts.csv; then
            echo "No updates"
          else
            echo "Updates available"
            echo "CHANGE=true" >> $GITHUB_OUTPUT
            mv _prompts.csv prompts.csv
          fi

      - name: Run converter
        id: convert
        working-directory: ./assets
        if: ${{ steps.change.outputs.CHANGE }}
        run: |
          if python csv2json.py prompts.csv ../prompts.json; then
            echo "Conversion successful"
            echo "CONVERT=true" >> $GITHUB_OUTPUT
          else
            echo "Conversion failed"
            exit 1
          fi

      - name: Commit files
        if: ${{ steps.convert.outputs.CONVERT }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./assets/prompts.csv prompts.json
          git commit -m "update prompts"

      - name: Push changes
        if: ${{ steps.convert.outputs.CONVERT }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
